<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Draxayani-PC" name="suite29" tests="5" failures="1" timestamp="5 Sep 2014 07:44:00 GMT" time="737.402" errors="0">
  <testcase name="verify" time="116.418" classname="com.adv.qa.selenium.tests.currency.phase2.A073_Receipt_ControlTest"/>
  <testcase name="verify" time="211.695" classname="com.adv.qa.selenium.tests.currency.phase2.A071_Document_PrefixCodesTest"/>
  <testcase name="verify" time="282.856" classname="com.adv.qa.selenium.tests.currency.phase2.A072_Common_Purchasing_UsersTest"/>
  <testcase name="verify" time="132.379" classname="com.adv.qa.selenium.tests.currency.phase2.A074_Automatic_Banking_CodeTest">
    <failure type="java.lang.AssertionError" message="New automatic bank code  AP not displayed in the list expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: New automatic bank code  AP not displayed in the list expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.adv.qa.selenium.framework.Assert.assertTrue(Assert.java:43)
	at com.adv.qa.selenium.tests.currency.phase2.A074_Automatic_Banking_CodeTest.verify(A074_Automatic_Banking_CodeTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verify -->
  <testcase name="verify" time="478.295" classname="com.adv.qa.selenium.tests.currency.phase2.A075_Circulation_CodeTest"/>
</testsuite> <!-- suite29 -->
