<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ChetnaM-PC" ignored="0" name="suite9" tests="5" failures="1" timestamp="24 May 2017 13:52:23 GMT" time="800.024" errors="0">
  <testcase name="verify" time="238.438" classname="com.adv.qa.selenium.tests.currency.phase2.A073_Receipt_ControlTest"/>
  <testcase name="verify" time="439.334" classname="com.adv.qa.selenium.tests.currency.phase2.A071_Document_PrefixCodesTest"/>
  <testcase name="verify" time="465.24" classname="com.adv.qa.selenium.tests.currency.phase2.A072_Common_Purchasing_UsersTest"/>
  <testcase name="verify" time="211.081" classname="com.adv.qa.selenium.tests.currency.phase2.A074_Automatic_Banking_CodeTest"/>
  <testcase name="verify" time="303.874" classname="com.adv.qa.selenium.tests.currency.phase2.A075_companyControl_MapOrderTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.adv.qa.selenium.tests.currency.phase2.A075_companyControl_MapOrderTest.verify() didn&amp;apos;t finish within the time-out 800000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.adv.qa.selenium.tests.currency.phase2.A075_companyControl_MapOrderTest.verify() didn't finish within the time-out 800000
	at java.lang.Thread.sleep(Native Method)
	at com.adv.qa.selenium.helpers.WaitHelper.waitAdditional(WaitHelper.java:245)
	at com.adv.qa.selenium.framework.pageObjects.currency.CurrencyPage.clickOnInsert1(CurrencyPage.java:300)
	at com.adv.qa.selenium.tests.currency.phase2.A075_companyControl_MapOrderTest.createMappings(A075_companyControl_MapOrderTest.java:123)
	at com.adv.qa.selenium.tests.currency.phase2.A075_companyControl_MapOrderTest.verify(A075_companyControl_MapOrderTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verify -->
</testsuite> <!-- suite9 -->
