<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ChetnaM-PC" name="com.adv.qa.selenium.tests.currency.A001A_On_line_AuditingTest" tests="1" failures="0" timestamp="22 Jun 2017 15:32:36 GMT" time="153.193" errors="1">
  <testcase name="verify" time="153.193" classname="com.adv.qa.selenium.tests.currency.A001A_On_line_AuditingTest">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.adv.qa.selenium.framework.pageObjects.currency.CurrencyPage.clickOnSections(CurrencyPage.java:815)
	at com.adv.qa.selenium.framework.pageObjects.currency.CurrencyPage.searchEntityValue(CurrencyPage.java:1574)
	at com.adv.qa.selenium.tests.currency.A001A_On_line_AuditingTest.verify(A001A_On_line_AuditingTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- verify -->
</testsuite> <!-- com.adv.qa.selenium.tests.currency.A001A_On_line_AuditingTest -->
